import Sidebar from "@/components/component/Sidebar";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex flex-row">
      <Sidebar/>
      {children}
      </div>
        
  );
}
