/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CVUGmXgGVQs
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Sheet, SheetTrigger, SheetContent, SheetClose } from "@/components/ui/sheet"
import { Input } from "@/components/ui/input"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"

export function Banner() {
  return (
    (<div className="flex flex-col h-screen">
      <header
        className="bg-white text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="#" className="text-lg font-semibold" prefetch={false}>
            Async Meeting
          </Link>
          <nav className="hidden md:flex items-center gap-4 text-sm font-medium">
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              Dashboard
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              Calendar
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              Chat
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" className="md:hidden">
            <MenuIcon className="w-6 h-6" />
            <span className="sr-only">Toggle menu</span>
          </Button>
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="flex-1 bg-background">
        <section
          className="py-20 px-6 md:px-10 lg:px-16 flex flex-col items-center justify-center h-full">
          <h1 className="text-4xl font-bold mb-4">Welcome to Async Meeting</h1>
          <p className="text-muted-foreground mb-8">
            Collaborate with your team and stay organized with our powerful meeting management tools.
          </p>
          <Link
            href="/homepage"
            className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-3 text-sm font-medium text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
            prefetch={false}>
            Get Started
          </Link>
        </section>
      </main>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="ghost" size="icon" className="fixed bottom-4 right-4 md:hidden">
            <PlusIcon className="w-6 h-6" />
            <span className="sr-only">New meeting</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="right" className="w-full max-w-md bg-background p-6">
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-xl font-semibold">New Meeting</h2>
            <SheetClose asChild>
              <Button variant="ghost" size="icon">
                <XIcon className="w-6 h-6" />
                <span className="sr-only">Close</span>
              </Button>
            </SheetClose>
          </div>
          <form>
            <div className="grid gap-4">
              <Input placeholder="Meeting title" />
              <div className="grid md:grid-cols-2 gap-4">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button variant="outline" className="flex-col items-start w-full h-auto">
                      <span className="font-semibold uppercase text-[0.65rem]">Start</span>
                      <span className="font-normal">4/2/2024, 10:00 AM</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0 max-w-[276px]">
                    <Calendar />
                  </PopoverContent>
                </Popover>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button variant="outline" className="flex-col items-start w-full h-auto">
                      <span className="font-semibold uppercase text-[0.65rem]">End</span>
                      <span className="font-normal">4/2/2024, 11:00 AM</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0 max-w-[276px]">
                    <Calendar />
                  </PopoverContent>
                </Popover>
              </div>
              <Textarea placeholder="Meeting description" rows={4} />
              <div className="grid gap-2">
                <Label htmlFor="participants">Participants</Label>
                <Select id="participants" multiple>
                  <SelectTrigger className="h-auto">
                    <SelectValue
                      placeholder={
                        <div className="flex flex-col items-start">
                          <span className="font-semibold uppercase text-[0.65rem]">Participants</span>
                          <span className="font-normal">2 participants</span>
                        </div>
                      } />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="john@example.com">John Doe</SelectItem>
                    <SelectItem value="jane@example.com">Jane Smith</SelectItem>
                    <SelectItem value="bob@example.com">Bob Johnson</SelectItem>
                    <SelectItem value="alice@example.com">Alice Williams</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <Button type="submit" className="w-full">
                Create Meeting
              </Button>
            </div>
          </form>
        </SheetContent>
      </Sheet>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function PlusIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
